### PR TITLE
Refactor laserscan comparison

### PR DESCRIPTION
**Pull request by martiniil**
## Description

These changes avoid confusion about the LaserScan equality operator.

It is not clear, if this operator should compare the timestamps and if it really should check measurements/intensities (double values!) for equality. So we remove it. In our code it is only used in tests where it can by replaced by a more descriptive matcher.

note: My first attempt of using Pointwise(DoubleEq(), ...) as matcher did not work with the googletest version on bionic.

Changes in detail:
- Refactor laserscan comparison
- Add ostream operator for better output in case of test failure

- [x] Rebase after #223 

### Things to add, update or check by the maintainers before this PR can be merged.

- [x] Public api function documentation
- [x] Architecture documentation reflects actual code structure
- [ ] ~[Tutorials](https://wiki.ros.org/pilz_robots/Tutorials/)~
- [ ] ~Overview on [ROS wiki](https://wiki.ros.org/pilz_robots)~
- [ ] ~Package Readme ([example pilz_robots](https://github.com/PilzDE/pilz_robots/blob/melodic-devel/README.md))~
- [x] Good commit messages ([some tips](https://dev.to/jacobherrington/how-to-write-useful-commit-messages-my-commit-message-template-20n9))
- [x] CHANGELOG.rst updated
- [x] Copyright headers
- [ ] ~Examples~

### Review Checklist
- [x] Soft- and hardware architecture (diagrams and description)
- [x] Test review (test plan and individual test cases)
- [x] Documentation describes purpose of file(s) and responsibilities
- [x] Code (coding rules, style guide)

### Release planning (please answer)
- [ ] ~When is the new feature released?~
- [ ] ~Which dependent packages do have to be released simultaneously?~

### Hardware tests
- [ ] Perform hardware tests

### CODE REVIEW

**Comment by agutenkunst** [comment]
@martiniil What is the issue with the Win Build?

**Comment by martiniil** [comment]
> 
> 
> @martiniil What is the issue with the Win Build?

I don't know yet. There is one single test case that fails. But so far I don't see a connection to these changes.

**Comment by martiniil** [comment]
> 
> 
> @martiniil What is the issue with the Win Build?

I found the issue: #228

**Review by ct2034 — APPROVED** [review]
Good change

**Pull request merged**
