### PR TITLE
Add wait in Scanner::start()

### PR DESCRIPTION
**Pull request by hslusarek**
This PR ensures that the `Scanner::start()` waits until a start reply is received from the scanner device.

### CODE REVIEW

**Comment by agutenkunst** [comment]
Looks good at first sight. Please rebase against feature/new_firmware and update the diagrams inside /doc

**Comment by hslusarek** [comment]
> Looks good at first sight. Please rebase against feature/new_firmware and update the diagrams inside /doc

Done.

**Comment by agutenkunst** [comment]
Looks good on real system! Thank you!

**Review by agutenkunst — APPROVED** [review]
Thank you!

**Pull request merged**
