### PR TITLE
Remove ALL_CAPS from enum class

### PR DESCRIPTION
**Pull request by agutenkunst**
See http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps

### CODE REVIEW

**Review by cdoehn — COMMENTED** [review]
Are this enums not something like constants? Then they should be capital:

http://wiki.ros.org/CppStyleGuide#Constants

I propose not to mix this styles. Let us decide for one rule

**Comment by agutenkunst** [comment]
Style was mixed before. Have a close look at all enums before this PR. Also check the reasoning at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps

**Comment by agutenkunst** [comment]
Ok seems that the ROS-Style wants https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html#cmdoption-arg-enumconstantcase to be UPPER_CASE see https://github.com/ros-planning/moveit/blob/master/.clang-tidy

Not sure what https://clang.llvm.org/extra/clang-tidy/checks/readability-identifier-naming.html#cmdoption-arg-scopedenumconstantcase does.

Also clang-tidy only detects the violations in cpp files. Thus lower_case is allowed in *.h files. 

How to proceed?

**Comment by martiniil** [comment]
> Style was mixed before. Have a close look at all enums before this PR. Also check the reasoning at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps

This suggests that ALL_CAPS is reserved for macros only. I think we don't need to do that.

**Comment by agutenkunst** [comment]
> > Style was mixed before. Have a close look at all enums before this PR. Also check the reasoning at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps
> 
> This suggests that ALL_CAPS is reserved for macros only. I think we don't need to do that.

So change .clang-tidy?

**Comment by martiniil** [comment]
> > > Style was mixed before. Have a close look at all enums before this PR. Also check the reasoning at http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps
> > 
> > 
> > This suggests that ALL_CAPS is reserved for macros only. I think we don't need to do that.
> 
> So change .clang-tidy?

No, I suggest we keep it like that.

**Comment by cdoehn** [comment]
I changed .clang-tidy to case style lower_case...
On my opinion it doesn't matter, which case style but it has to be consistent

**Comment by martiniil** [comment]
> I changed .clang-tidy to case style lower_case...
> On my opinion it doesn't matter, which case style but it has to be consistent

Ok for me

**Pull request merged**
